defaultEntryPoints = ["http", "https"]
    [entryPoints]
        [entryPoints.http]
        address = ":80"
            [entryPoints.http.redirect]
                entryPoint = "https"
        [entryPoints.https]
        address = ":443"
            [entryPoints.https.tls]

[acme]
email = "dashboard.mf2c-project.eu"
storage = "acme.json"
entryPoint = "https"
[acme.httpChallenge]
   entryPoint = "http"
[[acme.domains]]
   main = "dashboard.mf2c-project.eu"
