version: '3'
services:
  proxy:
    image: traefik
    restart: unless-stopped
    command: --web --docker --docker.exposedByDefault=false --loglevel=info
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - ./traefik/traefik.toml:/traefik.toml
    ports:
     - "80:80"
     - "443:443"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    restart: unless-stopped
    environment:
     - cluster.name=elasticsearch
     - xpack.security.enabled=false
     - discovery.type=single-node
     - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
  cimi:
    image: mf2c/cimi-server:latest
    expose:
     - "8201"
    restart: unless-stopped
    labels:
     - "traefik.enable=true"
     - "traefik.backend=cimi"
     - "traefik.frontend.rule=PathPrefix:/,/"
  COMPSs:
    image: mf2c/compss-mf2c:1.0
    expose: 
     - 8080
    restart: unless-stopped
  service-manager:
    image: mf2c/service-manager
    depends_on:
      - cimi
    expose:
      - 46200
    ports:
      - 46200:46200
  discovery:
    image: mf2c/discovery:latest
    depends_on:
      - cimi
    expose: 
      - 46040
    cap_add:
      - NET_ADMIN
  policies:
    image: mf2c/policies:latest
    depends_on:
      - discovery
    container_name: policies
    ports:
      - "46050"
      - "46051:46051"
      - "46052:46052"
  cau-client:
    image: mf2c/cau-client:v1.01
    depends_on:
#   assuming cau and leader cau are bootstrapped elsewhere
      - policies
    container_name: cau-client
    expose:
      - 46065
#   please provide ip:port params for CAU and leader CAU
    environment:
      - CAU_URL=
      - LCAU_URL=
  identification:
    image: mf2c/identification
    volumes:
      - mydata:/data
    expose:
      - 46060
  user-management:
    image: mf2c/user-management
    expose:
      - "46300"
    environment:
      - CIMI_URL=
  lifecycle:
    image: mf2c/lifecycle
    expose:
      - "46000"
    environment:
      - CIMI_URL=
      - STANDALONE_MODE=False
      - HOST_IP=
      - WORKING_DIR_VOLUME=/tmp/compose_files
    volumes:
      - /tmp/compose_files:/tmp/compose_files
      - /var/run/docker.sock:/var/run/docker.sock  
  resouce-categorization:
    image: mf2c/resource-categorization:latest
    depends_on:
      - cimi
    expose:
      - 46070
    privileged: true
      
volumes:
  mydata: {}
