version: '3'
services:
  proxy:
    image: traefik
    restart: unless-stopped
    command: --web --docker --docker.exposedByDefault=false --loglevel=info
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - ./traefik/traefik.toml:/traefik.toml
    ports:
     - "80:80"
     - "443:443"
  cimi:
    image: mf2c/cimi-server:1.3-SNAPSHOT
    expose:
     - "8201"
    restart: always
    labels:
     - "traefik.enable=true"
     - "traefik.backend=cimi"
     - "traefik.frontend.rule=PathPrefix:/,/"
  COMPSs:
    image: mf2c/compss-mf2c:1.0
    expose: 
     - 8080
    restart: always
