version: '3.4'
services:
  ####################### Proxy  ######################
  proxy:
    image: traefik
    restart: unless-stopped
    command: --web --docker --docker.exposedByDefault=false --loglevel=info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/cert:/ssl:ro
    ports:
      - "80:80"
      - "443:443"
  ######################################################

  ######################## CIMI  #######################
  cimi:
    image: mf2c/cimi-server:2.27
    restart: on-failure
    depends_on:
      - logicmodule1
      - dcproxy
    environment:
      - DC_HOST=dcproxy
      - DC_PORT=6472
      - EPHEMERAL_DB_BINDING_NS=com.sixsq.slipstream.db.dataclay.loader
      - PERSISTENT_DB_BINDING_NS=com.sixsq.slipstream.db.dataclay.loader
    expose:
      - "8201"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=cimi"
      - "traefik.frontend.rule=PathPrefix:/api"
    volumes:
      - ringcontainer:/opt/slipstream/ring-container
      - ringcontainerexample:/opt/slipstream/ring-example
    healthcheck:
      start_period: 30s
      retries: 5
      test: ["CMD", "wget", "--spider", "http://localhost:8201/api/cloud-entry-point"]

  rc:
    image: sixsq/ring-container:3.52
    expose:
      - "5000"
    volumes:
      - ringcontainer:/opt/slipstream/ring-container
      - ringcontainerexample:/opt/slipstream/ring-example
    command: sh

  #################### Dataclay  #######################
  dcproxy:
    image: mf2c/dataclay-proxy:2.23
    depends_on:
      - logicmodule1
      - ds1java1
    expose:
      - "6472"

  logicmodule1:
    image: mf2c/dataclay-logicmodule:2.23
    ports:
      - "1034:1034"
    environment:
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
      - LOGICMODULE_PORT_TCP=1034
      - LOGICMODULE_HOST=logicmodule1
    volumes:
      - ./prop/global.properties:/usr/src/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/dataclay/log4j2.xml:ro

  ds1java1:
    image: mf2c/dataclay-dsjava:2.23
    depends_on:
      - logicmodule1
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_HOST=ds1java1
      - DATASERVICE_JAVA_PORT_TCP=2127
      - LOGICMODULE_PORT_TCP=1034
      - LOGICMODULE_HOST=logicmodule1
    volumes:
      - ./prop/global.properties:/usr/src/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/dataclay/log4j2.xml:ro
  #####################################################

  ################### Event Manager ###################
  event-manager:
    image: mf2c/cimi-server-events:1.0
    depends_on:
      - cimi
    expose:
      - 8000
    restart: unless-stopped
  ######################################################

  ################## Service Manager ###################
  service-manager:
    image: mf2c/service-manager:1.8.2
    restart: unless-stopped
    depends_on:
      - cimi
    expose:
      - 46200
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/sm"
      - "traefik.port=46200"
    environment:
      - JAVA_OPTS=-Xms32m -Xmx256m
  ######################################################

  ########## Lifecycle Manager + User Manager ##########
  lm-um:
    image: mf2c/lifecycle-usermngt:1.2.6
    restart: on-failure
    depends_on:
      - cimi
      - resource-categorization
      - analytics-engine
      - landscaper
    expose:
      - "46300"
      - "46000"
    ports:
      - "46000:46000"
      - "46300:46300"
    environment:
      - HOST_IP=192.168.252.41
      - WORKING_DIR_VOLUME=/tmp/mf2c/compose_files
      - UM_WORKING_DIR_VOLUME=/tmp/mf2c/um/
      - LM_WORKING_DIR_VOLUME=/tmp/mf2c/lm/
      - SERVICE_CONSUMER=true
      - RESOURCE_CONTRIBUTOR=true
      - MAX_APPS=3
    volumes:
      - /tmp/mf2c/compose_files:/tmp/mf2c/compose_files
      - /tmp/mf2c/um:/tmp/mf2c/um
      - /tmp/mf2c/lm:/tmp/mf2c/lm
      - /var/run/docker.sock:/var/run/docker.sock
  ######################################################

  #################### SLA Manager #####################
  slalite:
    image: mf2c/sla-management:0.8.1
    restart: on-failure
    expose:
      - "46030"
  ######################################################

  ############ Resource Manager + Security #############
  policies:
     image: mf2c/policies:2.0.5
     restart: on-failure
     depends_on:
       - cimi
     ports:
       - "46050"
     labels:
       - "traefik.enable=true"
       - "traefik.frontend.rule=PathPrefix:/rm"
       - "traefik.port=46050"
     environment:
       - "DEBUG=True"
       - "MF2C=True"
       - "isLeader=${isLeader}"
       - "WIFI_DEV_FLAG=${WIFI_DEV_FLAG}"

  discovery:
     image: mf2c/discovery:1.4
     restart: on-failure
     depends_on:
       - cimi
     network_mode: "host"
     ports:
     - "46040:46040"
     cap_add:
       - NET_ADMIN

  identification:
     image: mf2c/identification:v2
     restart: on-failure
     volumes:
       - mydata:/data
     expose:
       - 46060

  cau-client:
     image: mf2c/cau-client-it2:v2.1
     depends_on:
       - policies
     volumes:
       - pkidata:/pkidata
     expose:
       - 46065
     #using the cloud cau for the moment
     environment:
       - CCAU_URL=213.205.14.13:55443
       - CAU_URL=213.205.14.13:55443

  aclib:
     image: mf2c/aclib:v1.0
     depends_on:
       - cau-client
     volumes:
       - pkidata:/pkidata
     expose:
       - 46080
     environment:
       - ACLIB_PORT=46080
       - CAUCLIENT_PORT=46065

  resource-categorization:
     image: mf2c/resource-categorization:latest-V2.0.18
     hostname: IRILD039
     restart: on-failure
     depends_on:
       - policies
     expose:
       - 46070
     privileged: true
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock

  ##### Analytics Engine + Recomender + Landscaper #####
  analytics-engine:
    image: mf2c/analytics-engine:0.5.5
    expose:
      - "46020"
    ports:
      - "46020:46020"
    depends_on:
      - influxdb
    volumes:
      - ./analytics_engine.conf:/root/analytics_engine/analytics_engine.conf
    labels:
      - "traefik.enable=true"
      - "traefik.port=46020"
      - "traefik.frontend.rule=PathPrefixStrip:/analytics-engine"

  landscaper:
    image: mf2c/landscaper:0.6.11
    volumes:
    - landscaper:/landscaper/data
    - ./landscaper.cfg:/landscaper/landscaper.cfg
    - ./ls_log:/landscaper/logs
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on: ["cimi", "neo4j", "proxy"]
    environment:
      - OS_TENANT_NAME=
      - OS_PROJECT_NAME=
      - OS_TENANT_ID=
      - OS_USERNAME=
      - OS_PASSWORD=
      - OS_AUTH_URL=
    command: ["./start.sh", "http://neo4j:7474"]

  telem_start:
    image: mf2c/telem_start:0.1
    command: sh /download.sh
    environment:
      - HOSTNAME
    depends_on:
      - snap

  influxdb:
    image: influxdb
    expose:
      - "8086"
    ports:
      - "8086:8086"
    volumes:
      - influx:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=snap
      - INFLUXDB_USER=snap
      - INFLUXDB_USER_PASSWORD=snap
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_USER_PASSWORD=admin
      - INFLUXDB_HTTP_LOG_ENABLED=false
  snap:
    image: intelsdi/snap:xenial
    hostname: snap
    ports:
      - "8181:8181"
    volumes: ['/proc:/proc_host', '/sys/fs/cgroup:/sys/fs/cgroup', '/var/run/docker.sock:/var/run/docker.sock']
    depends_on:
      - influxdb
    environment:
      - SNAP_VERSION=2.0.0
      - SNAP_LOG_LEVEL=2

  neo4j:
    image: neo4j:2.3.12
    privileged: true
    volumes:
      - neo4j:/data
    ports:
      - "7475:7474" # expose the port for the console ui
    environment:
      - NEO4J_AUTH=neo4j/password # neo4j requires change from default password, should reflect landscape.cfg

  web:
    image: mf2c/landscaper:0.6.5
    environment:
    - PYTHONPATH=/landscaper
    volumes:
      - ./landscaper.cfg:/landscaper/landscaper.cfg
      - ./ls_log:/collector_log
    ports:
      - "9001:9001"
    depends_on:
      - neo4j
      - landscaper
    command: ["/usr/local/bin/gunicorn", "-b", "0.0.0.0:9001", "-w", "2", "--chdir", "/landscaper/landscaper/web", "application:APP"]

  vpnclient:
    image: mf2c/vpnclient:1.1.0
    depends_on:
      - cau-client
    network_mode: "host"
    extra_hosts:
      - "vpnserver:213.205.14.13"
    environment:
      - VPN_DAEMON=FALSE
    cap_add:
      - NET_ADMIN
    volumes:
      - pkidata:/pkidata

  resource-bootstrap:
    image: mf2c/resource-bootstrap:1.0.0
    restart: "no"
    environment:
      - CIMI_HOST=proxy
      - CIMI_PORT=80
    depends_on:
      - proxy
      - cimi

######################################################

volumes:
  mydata: {}
  influx: {}
  influx-analytics: {}
  neo4j: {}
  landscaper: {}
  ringcontainer: {}
  ringcontainerexample: {}
  pkidata: {}
